// src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { ButtonComponent } from './shared/component/button/button.component';
import { SidebarComponent } from './shared/component/sidebar/sidebar.component';

@Component({
  selector: 'app-root',
  standalone: true,
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
  imports: [RouterOutlet, SidebarComponent, ButtonComponent],
})
export class AppComponent {
  title = 'culqi-demos';

  reset(): void {
    console.log('reset');
    window.location.reload();
  }
}

<div class="w-full h-full flex">
  <div
    class="max-w-7xl mt-10 mx-auto w-full flex flex-col sm:flex-row flex-grow overflow-hidden"
  >
    <app-sidebar></app-sidebar>
    <div
      class="w-full p-6 px-6 grid grid-cols-1 gap-4 place-content-center place-items-center"
    >
      <h1 class="my-6 text-xl font-bold text-center">PYTHON DEMO</h1>
      <h2 class="text-xl font-bold text-purple-800">CULQI - CUSTOM CHECKOUT</h2>

      <router-outlet></router-outlet>

      <div class="mt-20">
        <app-button
          [text]="'Reiniciar'"
          [type]="'primary'"
          (onClick)="reset()"
        ></app-button>
      </div>
    </div>
  </div>
</div>

// src/App.jsx
import React from "react";
import { OnlyCharge, WithCard } from "./pages";
import Sidebar from "./components/Sidebar";
import { BrowserRouter, Route, Routes } from "react-router-dom";

const App = () => {
  return (
    <BrowserRouter>
      <div className="w-full h-full">
        <div className="max-w-7xl mt-10 mx-auto w-full flex flex-col sm:flex-row flex-grow overflow-hidden">
          <Sidebar />
          <div className="w-full p-6 px-6 grid grid-cols-1 gap-4 place-content-center place-items-center">
            <h1 className="my-6 text-xl font-bold text-center">PYTHON DEMO</h1>
            <h2 className="text-xl font-bold text-purple-800">
              CULQI - CUSTOM CHECKOUT
            </h2>

            <Routes>
              <Route path="/" element={<OnlyCharge />} />
              <Route path="/with-card" element={<WithCard />} />
            </Routes>

            <div className="mt-20">
              <button
                className="bg-blue-500 hover:bg-blue-700 px-5 py-4 leading-5 rounded-full font-semibold text-white text-2xl"
                id="reset"
                onClick={() => window.location.reload(false)}
              >
                Reiniciar
              </button>
            </div>
          </div>
        </div>
      </div>
    </BrowserRouter>
  );
};

export default App;
